#! /bin/sh

bspc config border_width        4
bspc config window_gap          8
bspc config top_padding         24
bspc config split_ratio         0.51
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color  "#C5C8C6"
bspc config active_border_color   "#C5C8C6"
bspc config normal_border_color   "#5E6266"
bspc config presel_border_color   "#DE935F"

bspc monitor -d ⠁ ⠉ ⠋ ⠛ ⠟ ⠿

PANEL_FIFO="/tmp/panel-fifo"
~/.config/bspwm/panel/panel &
